branch-defaults:
  default:
    environment: flask-env-1
    group_suffix: null
  master:
    environment: flask-env-1
environment-defaults:
  flask-env-1:
    branch: null
    repository: null
global:
  application_name: fotyf
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
